services:
  - type: web
    name: backend
    runtime: docker
    repo: "https://github.com/ImTheChosen0ne/Java-web-app"
    branch: dev
    rootDir: .
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar backend.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "production"
      - key: SPRING_DATASOURCE_URL
        fromEnv: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnv: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnv: SPRING_DATASOURCE_PASSWORD
      - key: SCHEMA
        fromEnv: SCHEMA
      - key: PORT
        value: 8080

  - type: web
    name: frontend
    runtime: docker
    repo: "https://github.com/ImTheChosen0ne/Java-web-app"
    branch: dev
    rootDir: src/main/frontend/react-app
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: backend
          property: "http://localhost:8080"
      - key: PORT
        value: 3000

envVarGroups:
  - name: backend-env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-database
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-database
          property: password
