services:
  - type: web
    name: backend
    runtime: docker
    repo: "https://github.com/ImTheChosen0ne/Java-web-app"
    branch: dev
    rootDir: Java-web-app
    dockerCommand: ./Java-web-app.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "production"
      - key: SPRING_DATASOURCE_URL
        value: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        value: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        value: SPRING_DATASOURCE_PASSWORD
      - key: SCHEMA
        value: SCHEMA
      - key: PORT
        value: 8080

  - type: web
    name: frontend
    runtime: docker
    repo: "https://github.com/ImTheChosen0ne/Java-web-app"
    branch: dev
    rootDir: src/main/frontend/react-app
    dockerCommand: src/main/frontend/react-app.sh
    envVars:
      - key: REACT_APP_API_URL
      - value: REACT_APP_API_URL
      - key: PORT
        value: 3000

envVarGroups:
  - name: backend-env
    envVars:
      - key: DATABASE_URL
        value: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        value: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        value: SPRING_DATASOURCE_PASSWORD
