spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        #        driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            #            ddl-auto: update
            ddl-auto: none
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                default_schema: ${SCHEMA}
        #        database: mysql
        database: postgresql

        #        database-platform: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            schema-locations: classpath:schema_init.sql